development:
  host: "192.168.0.238"
  port: 27017
  database: test
  
test:
  host: "192.168.0.238"
  port: 27017
  database: test
  
staging:
  host: "192.168.2.21"
  port: 27017
  database: test
  
production:
  host: "192.168.2.21"
  port: 27017
  database: test 