development:
  scheme: http
  host: "192.168.0.238"
  port: 80
  bucket: "nb"
  
test:
  scheme: http
  host: "192.168.0.238"
  port: 80
  bucket: "nb"
  
staging:
  scheme: http
  host: "122.224.5.210"
  port: 38889
  bucket: "test"
  
production:
  scheme: http
  host: "122.224.5.210"
  port: 38889
  bucket: "test"
